# Generated by Django 2.0.2 on 2018-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanse_nr', models.IntegerField(max_length=3)),
                ('ant_steg', models.IntegerField(max_length=3)),
                ('ant_akt', models.IntegerField(max_length=3)),
                ('auto_man', models.IntegerField(max_length=1)),
                ('man_steg', models.IntegerField(max_length=10)),
                ('trykk', models.IntegerField(max_length=300)),
            ],
        ),
    ]
