# Generated by Django 2.0.2 on 2018-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanse',
            name='ant_akt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='ant_steg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='auto_man',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='lanse_nr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='man_steg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='trykk',
            field=models.IntegerField(),
        ),
    ]
