# Generated by Django 2.0.2 on 2018-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0002_auto_20180307_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanse',
            name='test',
            field=models.IntegerField(default=123),
        ),
    ]
