# Generated by Django 2.0.2 on 2018-03-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0003_lanse_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanse',
            name='test',
        ),
    ]
