# Generated by Django 2.0.2 on 2018-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0004_remove_lanse_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
