# Generated by Django 2.0.2 on 2018-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startside', '0007_led'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lansetyper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanseid', models.IntegerField(default=None)),
                ('lansetype', models.CharField(default=None, max_length=100)),
                ('ant_steg', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='lanse',
            name='ant_akt',
        ),
        migrations.RemoveField(
            model_name='lanse',
            name='ant_steg',
        ),
        migrations.RemoveField(
            model_name='lanse',
            name='lanse_nr',
        ),
        migrations.AddField(
            model_name='lanse',
            name='flow',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='lanse',
            name='lanse_kategori',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='lanse',
            name='lokal_maling',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='lanse',
            name='luftfukt',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='lanse',
            name='plassering_bronn',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='lanse',
            name='temperatur',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='lanse',
            name='timestamp',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='auto_man',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='man_steg',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='lanse',
            name='trykk',
            field=models.IntegerField(default=None),
        ),
    ]
