/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * How to setup clock using clock driver functions:
 *
 * 1. call CLOCK_SetSimSafeDivs() to set the system clock dividers in SIM to safe value.
 *
 * 2. If external oscillator is used Call CLOCK_SetXtal0Freq() to set XTAL0 frequency based on board settings and
 *    call CLOCK_InitOsc0() to init the OSC.
 *
 * 3. Call CLOCK_BootToXxxMode()/CLOCK_SetXxxMode() to set ICS run at the target mode.
 *
 * 4. If ICSIRCLK is needed, call CLOCK_SetInternalRefClkConfig() to enable the clock.
 *
 * 5. call CLOCK_SetSimConfig() to configure the divider in sim.
 */

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Clocks v4.0
processor: MKE02Z64xxx4
package_id: MKE02Z64VLH4
mcu_data: ksdk2_0
processor_version: 3.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

#include "clock_config.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
/* System clock frequency. */
extern uint32_t SystemCoreClock;

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
}

/*******************************************************************************
 ********************** Configuration BOARD_BootClockRUN ***********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockRUN
outputs:
- {id: Bus_clock.outFreq, value: 10 MHz}
- {id: Core_clock.outFreq, value: 10 MHz}
- {id: Flash_clock.outFreq, value: 10 MHz}
- {id: ICSFF_clock.outFreq, value: 39.0625/2 kHz}
- {id: LPO_clock.outFreq, value: 1 kHz}
- {id: OSCER_clock.outFreq, value: 10 MHz}
- {id: Plat_clock.outFreq, value: 10 MHz}
- {id: System_clock.outFreq, value: 10 MHz}
settings:
- {id: ICSMode, value: FBE}
- {id: ICS.BDIV.scale, value: '1', locked: true}
- {id: ICS.CLKS.sel, value: OSC.OSCCLK}
- {id: ICS.IREFS.sel, value: ICS.RDIV}
- {id: ICS.RDIV.scale, value: '256'}
- {id: OSC_CR_OSCEN_CFG, value: Enabled}
- {id: OSC_CR_RANGE_CFG, value: High}
- {id: OSC_CR_RANGE_RDIV_CFG, value: High}
sources:
- {id: OSC.OSC.outFreq, value: 10 MHz, enabled: true}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Variables for BOARD_BootClockRUN configuration
 ******************************************************************************/
const ics_config_t icsConfig_BOARD_BootClockRUN =
    {
        .icsMode = kICS_ModeFBE,                  /* FBE - FLL Bypassed External */
        .irClkEnableMode = 0,                     /* ICSIRCLK disabled */
        .bDiv = 0x0U,                             /* Bus clock divider: divided by 1 */
        .rDiv = 0x3U,                             /* FLL external reference clock divider: divided by 256 */
    };
const sim_clock_config_t simConfig_BOARD_BootClockRUN =
    {
        .busDiv = 0x0U,                           /* BUSDIV clock divider: divided by 1 */
        .busClkPrescaler = 0x0U,                  /* bus clock optional prescaler */
    };
const osc_config_t oscConfig_BOARD_BootClockRUN =
    {
        .freq = 10000000U,                        /* Oscillator frequency: 10000000Hz */
        .workMode = 0,                            /* Use external clock */
        .enableMode = kOSC_Enable,                /* Enable external reference clock, disable external reference clock in STOP mode */
    };

/*******************************************************************************
 * Code for BOARD_BootClockRUN configuration
 ******************************************************************************/
void BOARD_BootClockRUN(void)
{
    /* Set the system clock dividers in SIM to safe value. */
    CLOCK_SetSimSafeDivs();
    /* Initializes OSC0 according to board configuration. */
    CLOCK_InitOsc0(&oscConfig_BOARD_BootClockRUN);
    CLOCK_SetXtal0Freq(oscConfig_BOARD_BootClockRUN.freq);
    /* Set ICS to FBE mode. */
    CLOCK_SetFbeMode(icsConfig_BOARD_BootClockRUN.bDiv,
                     icsConfig_BOARD_BootClockRUN.rDiv);
    /* Set the clock configuration in SIM module. */
    CLOCK_SetSimConfig(&simConfig_BOARD_BootClockRUN);
    /* Set SystemCoreClock variable. */
    SystemCoreClock = BOARD_BOOTCLOCKRUN_CORE_CLOCK;
}

